### PR TITLE
Update NodeJS packages

### PR DESCRIPTION
**Pull request by dforsber**
- `npm-check-updates -u`
- edit `package.json` and make all third/patch level versions as x
- `test/run.sh` does not complain, see output below:
```
2015-02-04T08:25:57.271Z INFO logger: log stream opened
2015-02-04T08:25:57.284Z INFO server: log synchronization server starting
2015-02-04T08:26:00.283Z INFO logger: log stream opened
2015-02-04T08:26:00.317Z INFO client: starting log synchronization
2015-02-04T08:26:00.319Z DEBUG scanner: scanning for new files
2015-02-04T08:26:00.347Z DEBUG scanner: scan for new files finished
2015-02-04T08:26:03.210Z INFO client: stopping log synchronization
2015-02-04T08:26:03.215Z INFO logger: log stream closed
2015-02-04T08:26:03.221Z INFO server: log synchronization server stopping
2015-02-04T08:26:03.221Z INFO logger: log stream closed
```

### CODE REVIEW

**Comment by dforsber** [comment]
https://david-dm.org/poplatek/shaftlog#info=devDependencies&view=list
Shows that all packets are updated, but I guess this is due to the major.minor.patch "pinned" versions in pakcage.json -file. Should use `^<major>.x` or `^<major>.<minor>.x`?

**Comment by nakedible-p** [comment]
The correct way to do updates is to run `npm install browserify@* --save-dev` for each package, and test that shaftlog works after each update. Updating all packages at once is likely to create hard to debug api changes.

**Comment by dforsber** [comment]
package.json updated with that and without any "x"s.

**Comment by nakedible-p** [comment]
There's still versions with `.x`, where there was one before.

**Comment by dforsber** [comment]
Tested with these new packages and fresh filesystem and logs are nicely flowing. Not going to test anymore as it seems to be fine.

**Comment by dforsber** [comment]
@nakedible-p Do you want "^" instead of "~" in front of the package versions in `package.json`?

**Comment by dforsber** [comment]
I had shaftlog server stopped a long time. When I started it, logs started to flow nicely and `shaftlog-client.log` started to show no sync errors anymore.

**Comment by dforsber** [comment]
Well, now using "^" instead of "~". I guess the "~" came automatically from the `npm install <pkg>@* --save-dev` command.

**Comment by dforsber** [comment]
IMO ready to rok.

**Comment by nakedible** [comment]
Good to go.

**Pull request merged**
